name: "Roam Research backup"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Clone roam2github Repository
        run: |
          cd /tmp
          git clone -q https://github.com/everruler12/roam2github.git roam2github
          cd roam2github
      
      - name: Install Dependencies and Fix Vulnerabilities
        working-directory: /tmp/roam2github
        run: |
          npm install
          npm audit fix
          npm install rimraf@latest inflight@latest glob@latest puppeteer@latest
      
      - name: Commit and Push Changes
        working-directory: /tmp/roam2github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://xinyiheng:${{ secrets.GITHUB_TOKEN }}@github.com/xinyiheng/roam-backup.git
          git pull origin main --rebase
          git add package-lock.json
          git commit -m "Update package-lock.json and dependencies"
          git push origin main  # 推送更改到你的仓库
      
      - name: Run Backup
        working-directory: /tmp/roam2github
        run: |
          npm run start -s
        env:
          R2G_EMAIL: ${{ secrets.R2G_EMAIL }}
          R2G_PASSWORD: ${{ secrets.R2G_PASSWORD }}
          R2G_GRAPH: ${{ secrets.R2G_GRAPH }}

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated snapshot
        
