name: "Roam Research backup"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # 升级到 Node.js 20
      
      - name: Run Backup
        run: |
          cd /tmp/roam2github
          npm run start -s
        env:
          R2G_EMAIL: ${{ secrets.R2G_EMAIL }}
          R2G_PASSWORD: ${{ secrets.R2G_PASSWORD }}
          R2G_GRAPH: ${{ secrets.R2G_GRAPH }}

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated snapshot
